image: "python:3.4"

before_script:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y locales openssh-client wget zip unzip tar python3-gi python3-gi-cairo python3-cairo gir1.2-gtk-3.0 libdbus-1-dev libdbus-glib-1-dev libffi-dev build-essential libssl-dev python3-dev libgdk-pixbuf2.0-dev
  - sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && dpkg-reconfigure --frontend=noninteractive locales && update-locale LANG=en_US.UTF-8

  # SSH key and known hosts handling
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan download.kiwix.org >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

build-pibox-image:
  stage: build
  variables:
    LANG: 'en_US.UTF-8'
  script:
    - touch atest.zip
    - scp atest.zip ci@download.kiwix.org:/data/download/hotspots/base/
  only:
    - schedules
    - web
