before_install:
- openssl aes-256-cbc -K $encrypted_af8ee76d875e_key -iv $encrypted_af8ee76d875e_iv -in travis_secrets.tar.enc -out travis_secrets.tar -d
- tar xvf travis_secrets.tar
- chmod 600 pibox_installer_ci_rsa

matrix:
  include:
  - os: linux
    language: python
    python: 3.4
    dist: trusty
    # group: deprecated-2017Q2
    sudo: required
    virtualenv:
      system_site_packages: true
    addons:
      apt:
        packages:
          # Some package may not be required
          python3-gi
          python3-gi-cairo
          python3-cairo
          gir1.2-gtk-3.0
          libdbus-1-dev
          libdbus-glib-1-dev
          libffi-dev
          build-essential
          libssl-dev
          python-dev
          python3-dev
          libgdk-pixbuf2.0-dev
    install:
    script:
    # Install python dependancies
    - pip3 install -r requirements-linux.txt

    # Install and run pyinstaller
    # note: we use mgautierfr version because it resolves packaging pygobject
    - pip3 install https://github.com/mgautierfr/pyinstaller/archive/xlib_hook.zip
    - pyinstaller --log-level=DEBUG gi_example.spec
    - cat build/pibox-installer-linux/warngi_example.txt

    # Archive
    - cd dist
    - tar czvf pibox-installer.tar.gz pibox-installer
    - cd ..

    # Deploy
    - scp -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa dist/pibox-installer.tar.gz pibox_ci@buildbot.wan.bsf-intranet.org:/srv/repos/pibox/$(date +"%Y-%m-%d")/pibox-installer-linux-debug.tar.gz

    - PIBOX_RELEASE=$(git tag -l --points-at HEAD | grep -x 'v[[:digit:]]\+.[[:digit:]]\+\(.[[:digit:]]\+\)*') || true
    - if [ $PIBOX_RELEASE ]; then scp -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa dist/pibox-installer.tar.gz pibox_ci@buildbot.wan.bsf-intranet.org:/srv/repos/pibox/pibox-installer-$PIBOX_RELEASE-linux.tar.gz; fi
