before_install:
- openssl aes-256-cbc -K $encrypted_af8ee76d875e_key -iv $encrypted_af8ee76d875e_iv -in travis_secrets.tar.enc -out travis_secrets.tar -d
- tar xvf travis_secrets.tar
- chmod 600 pibox_installer_ci_rsa

addons:
  ssh_known_hosts:
  - download.kiwix.org
  - tmp.kiwix.org

matrix:
  include:
  - language: python
    python: 3.6
    sudo: false
    install:
    - pip install -r ansiblecube/tests/requirements-dev.txt
    script:
    - cd ansiblecube
    - py.test

  - os: osx
    osx_image: xcode10.1
    language: generic
    python: 3.7.1  # just a label
    install:
    - PIBOX_RELEASE=$(echo $TRAVIS_TAG | grep -x 'v[[:digit:]]\+.[[:digit:]]\+\(.[[:digit:]]\+\)*\(-rc[[:digit:]]\+\)\?') || true
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - SCOMMIT=$(git rev-parse --short ${TRAVIS_COMMIT})
    - if [ $PIBOX_RELEASE ]; then PIBOX_VERSION=${PIBOX_RELEASE:1}; elif [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then PIBOX_VERSION="nightly ($SCOMMIT)"; else PIBOX_VERSION="CI ($SCOMMIT)"; fi
    - sed -i.bak "s/VERSION = \"devel\"/VERSION = \"${PIBOX_VERSION}\"/g" kiwix-hotspot/data.py

    # Package kiwix-hotspot
    - brew update
    # checking our formulas out to how they were when python 3.6.5 was around
    # - cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
    # - git checkout e128fa1bce3377de32cbf11bd8e46f7334dfd7a6 Formula/python.rb Formula/pygobject.rb Formula/pygobject3.rb Formula/py2cairo.rb Formula/py3cairo.rb Formula/cairo.rb Formula/gtk+3.rb Formula/glib.rb Formula/adwaita-icon-theme.rb Formula/gobject-introspection.rb Formula/gdk-pixbuf.rb Formula/harfbuzz.rb Formula/pango.rb Formula/atk.rb
    # - cd -
    - brew install pygobject3 gtk+3 adwaita-icon-theme
    # needed for create-dmg
    - brew switch icu4c 62.1
    - python3 -m pip install -U pip
    - python3 -m pip install -r requirements-macos.txt
    - python3 -m pip install -U pyinstaller
    # following line needed locally (venv)
    #- ln -s /usr/local/lib/python3.7/site-packages/gi $(python3 -c "import sys; print(sys.path[-1])")/
    # - python3 -m pip install https://github.com/pyinstaller/pyinstaller/archive/93eec04eb2fbfc714d2c3453e04fd126e6a86f52.zip

    # Download vexpress-boot
    - wget http://mirror.download.kiwix.org/dev/vexpress-boot.zip
    - unzip vexpress-boot.zip

    # Bundle QEMU
    - wget http://mirror.download.kiwix.org/dev/qemu-2.12.0_macOS.tar
    - tar xf qemu-2.12.0_macOS.tar

    # Bundle Etcher-cli
    - wget http://download.kiwix.org/dev/balena-etcher-cli-1.4.8-darwin-x64.tar.gz
    - mkdir -p etcher-cli
    - tar xf balena-etcher-cli-1.4.8-darwin-x64.tar.gz -C etcher-cli --strip-components=1

    # Run PyInstaller
    - pyinstaller --log-level=DEBUG kiwix-hotspot-macos.spec

    # fix gdk-pixbuf for codesign (https://github.com/pyinstaller/pyinstaller/pull/2596)
    - mv dist/Kiwix\ Hotspot.app/Contents/MacOS/lib/gdk-pixbuf-2.0/2.10.0 dist/Kiwix\ Hotspot.app/Contents/MacOS/lib/gdk-pixbuf
    - rm -rf dist/Kiwix\ Hotspot.app/Contents/MacOS/lib/gdk-pixbuf-2.0

    # Sign application
    - security create-keychain -p mysecretpassword build.keychain
    - security default-keychain -s build.keychain
    - security unlock-keychain -p mysecretpassword build.keychain
    - security import pibox-installer.p12 -k build.keychain -P $MACOS_CERTIFICATE_PASSWORD -A
    - "security set-key-partition-list -S apple-tool:,apple: -s -k mysecretpassword build.keychain"
    - security find-identity -v
    - "codesign -s \"Developer ID Application: Wikimedia CH (L7HWM3SP3L)\" \"dist/Kiwix Hotspot.app\" --deep"

    # Install and run create-dmg
    - npm install --global create-dmg
    - create-dmg dist/Kiwix\ Hotspot.app
    - mv Kiwix-Hotspot-*.dmg kiwix-hotspot-macos.dmg

    # CI build
    - if [ "$TRAVIS_EVENT_TYPE" != "cron" ] && [ "a$PIBOX_RELEASE" = "a" ]; then scp -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa kiwix-hotspot-macos.dmg ci@tmp.kiwix.org:/data/tmp/ci/kiwix-hotspot-macos-$BRANCH.dmg; fi
    # nightly build (cron master)
    - if [ "$TRAVIS_EVENT_TYPE" = "cron" ] && [ "a$PIBOX_RELEASE" = "a" ]; then SRCDIR=nightly/$(date +'%Y-%m-%d'); mkdir -p $SRCDIR; cp kiwix-hotspot-macos.dmg $SRCDIR/; scp -r -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa $SRCDIR ci@download.kiwix.org:/data/download/nightly/; fi
    # release build (tagged)
    - if [ "$TRAVIS_EVENT_TYPE" != "cron" ] && [ $PIBOX_RELEASE ]; then mkdir -p releases/$PIBOX_RELEASE; cp kiwix-hotspot-macos.dmg releases/$PIBOX_RELEASE/; scp -r -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa releases/$PIBOX_RELEASE ci@download.kiwix.org:/data/download/release/kiwix-hotspot/; fi

  - os: linux
    language: python
    python: 3.4
    dist: trusty
    sudo: required
    virtualenv:
      system_site_packages: true
    addons:
      apt:
        packages:
          # Some package may not be required
          python3-gi
          python3-gi-cairo
          python3-cairo
          gir1.2-gtk-3.0
          libdbus-1-dev
          libdbus-glib-1-dev
          libffi-dev
          build-essential
          libssl-dev
          python-dev
          python3-dev
          libgdk-pixbuf2.0-dev
    script:
    - PIBOX_RELEASE=$(echo $TRAVIS_TAG | grep -x 'v[[:digit:]]\+.[[:digit:]]\+\(.[[:digit:]]\+\)*\(-rc[[:digit:]]\+\)\?') || true
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - SCOMMIT=$(git rev-parse --short ${TRAVIS_COMMIT})
    - if [ $PIBOX_RELEASE ]; then PIBOX_VERSION=${PIBOX_RELEASE:1}; elif [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then PIBOX_VERSION="nightly ($SCOMMIT)"; else PIBOX_VERSION="CI ($SCOMMIT)"; fi
    - sed -i.bak "s/VERSION = \"devel\"/VERSION = \"${PIBOX_VERSION}\"/g" kiwix-hotspot/data.py

    # update XZ (trusty version -5.0.5 is too old)
    - wget http://mirror.download.kiwix.org/dev/xz-5.2.4.tar.gz
    - tar xf xz-5.2.4.tar.gz
    - cd xz-5.2.4
    - ./configure --enable-shared
    - make
    - sudo make install
    - sudo ldconfig
    - cd ..

    # Download vexpress-boot
    - wget http://mirror.download.kiwix.org/dev/vexpress-boot.zip
    - unzip vexpress-boot.zip

    # get static QEMU
    - wget http://mirror.download.kiwix.org/dev/qemu-2.12.0-linux-x86_64.tar.gz
    - tar xf qemu-2.12.0-linux-x86_64.tar.gz

    # Bundle Etcher-cli
    - wget http://download.kiwix.org/dev/balena-etcher-cli-1.4.8-linux-x64.tar.gz
    - mkdir -p etcher-cli
    - tar xf balena-etcher-cli-1.4.8-linux-x64.tar.gz -C etcher-cli --strip-components=1

    # Install python dependancies
    - pip3 install -r requirements-linux.txt

    # Install and run pyinstaller
    # note: we temporary use a fork that resolves pygobject issues
    - pip3 install https://github.com/thiolliere/pyinstaller/archive/develop.zip
    - pyinstaller --log-level=DEBUG kiwix-hotspot-linux.spec
    - cat build/kiwix-hotspot-linux/warnkiwix-hotspot-linux.txt

    # Archive
    - cd dist
    - tar czvf kiwix-hotspot-linux.tar.gz kiwix-hotspot
    - cd ..

    # CI build
    - if [ "$TRAVIS_EVENT_TYPE" != "cron" ] && [ "a$PIBOX_RELEASE" = "a" ]; then scp -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa dist/kiwix-hotspot-linux.tar.gz ci@tmp.kiwix.org:/data/tmp/ci/kiwix-hotspot-linux-$BRANCH.tar.gz; fi
    # nightly build (cron master)
    - if [ "$TRAVIS_EVENT_TYPE" = "cron" ] && [ "a$PIBOX_RELEASE" = "a" ]; then SRCDIR=nightly/$(date +'%Y-%m-%d'); mkdir -p $SRCDIR; cp dist/kiwix-hotspot-linux.tar.gz $SRCDIR/; scp -r -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa $SRCDIR ci@download.kiwix.org:/data/download/nightly/; fi
    # release build (tagged)
    - if [ "$TRAVIS_EVENT_TYPE" != "cron" ] && [ $PIBOX_RELEASE ]; then mkdir -p releases/$PIBOX_RELEASE; cp dist/kiwix-hotspot-linux.tar.gz releases/$PIBOX_RELEASE/; scp -r -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa releases/$PIBOX_RELEASE ci@download.kiwix.org:/data/download/release/kiwix-hotspot/; fi
